CREATE DATABASE IF NOT EXISTS zhengyulinshop;
USE zhengyulinshop;

DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS users (
    uid INT(11) NOT NULL AUTO_INCREMENT,
    username VARCHAR(32) CHARACTER SET utf8 NOT NULL,
    password VARCHAR(255) CHARACTER SET utf8 NOT NULL,
    phone VARCHAR(20) CHARACTER SET utf8 NOT NULL,
    email VARCHAR(50) CHARACTER SET utf8 NOT NULL,
    PRIMARY KEY (uid)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
